# Generated by Django 3.2.6 on 2021-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=10)),
                ('last_logout', models.DateTimeField(auto_now=True, verbose_name='last logout')),
                ('failed_attempt', models.BooleanField(default=False)),
                ('blocker_timer', models.DateTimeField(auto_now=True, verbose_name='last logout')),
                ('otp_secret_token', models.CharField(max_length=100)),
                ('otp_client_token', models.CharField(max_length=100)),
                ('twofa_client_token', models.CharField(max_length=100)),
                ('twofa_secret_token', models.CharField(max_length=100)),
                ('is_email_verified', models.PositiveIntegerField(default=0)),
                ('is_mobile_verified', models.PositiveIntegerField(default=0)),
                ('is_otp_required', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
